---
- name: Dependencies
  sudo: yes
  yum: name={{ item }} state=latest
  with_items:
    - git-core

- name: Get InfluxDB Source
  git: repo={{ influxdb.git }} dest=go/{{ influxdb.src }} accept_hostkey=yes

- name: InfluxDB install, build, test
  shell: "cd go/{{ influxdb.src }}/;GOPATH=~/go GOROOT=~/bin/go ~/bin/go/bin/{{ item }}"
  with_items:
    - go get -d -v ./...
    - go build -v ./...
    - go get -u golang.org/x/tools/cmd/vet;
    - go test -v . ./messaging ./influxql;
    - go tool vet .
